# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - python -m scripts.setup

builds:
  - id: rsp-dump
    main: ./cmd/rsp-dump
    binary: rsp-dump
    goos: [ linux, windows ]
    goarch: [ amd64, arm64 ]
    env: [ CGO_ENABLED=0 ]
    flags: [ -trimpath ]
    ldflags: [ -s -w ]
  - id: rsp-dump-aws-lambda
    main: ./cmd/rsp-dump-aws-lambda
    binary: bootstrap
    goos: [ linux ]
    goarch: [ amd64 ]
    env: [ CGO_ENABLED=0 ]
    flags: [ -trimpath ]
    ldflags: [ -s -w ]
  - id: rsp-dump-cf-workers
    main: ./cmd/rsp-dump-cf-workers
    binary: app
    goos: [ js ]
    goarch: [ wasm ]
    env: [ CGO_ENABLED=0 ]
    flags: [ -trimpath ]
    ldflags: [ -s -w ]
    hooks:
      pre:
        - cmd: go run github.com/syumai/workers/cmd/workers-assets-gen -mode=go -o ./dist/rsp-dump-cf-workers_js_wasm 

archives:
  - id: rsp-dump
    format: tar.gz
    builds: [ rsp-dump ]
    name_template: "rsp-dump_{{ .Os }}_{{ .Version }}_{{ .Arch }}"
    wrap_in_directory: true
    files: [ rsp-*.json ]
  - id: rsp-dump-aws-lambda
    format: zip
    builds: [ rsp-dump-aws-lambda ]
    name_template: "rsp-dump-aws-lambda_{{ .Version }}_{{ .Arch }}"
    files: [ rsp-*.json ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
